### ISSUE TITLE
Pls update this plugin. miio already updated.

### ISSUE THREAD

**Issue by philboycn** [seikan/homebridge-mi-camera#3]
miio 0.14.01

{ Error: Call to device timed out                                                                                                                                     
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/miio/lib/device.js:229:18)                                                                          
    at ontimeout (timers.js:386:14)                                                                                                                                   
    at tryOnTimeout (timers.js:250:5)                                                                                                                                 
    at Timer.listOnTimeout (timers.js:214:5) code: 'timeout' }

**Comment by seikan** [comment]
Updated :)
