### ISSUE TITLE
Can't execute homebridge with Dafang cam.

### ISSUE THREAD

**Issue by Solusan** [seikan/homebridge-mi-camera#5]
Hello,

I'm completely stucked trying to execute homebridge with the config.json without syntax errors.

 in this point stops:

`/usr/lib/node_modules/homebridge-mi-camera/index.js:46
		this.device = miio.createDevice({
		                   ^

TypeError: miio.createDevice is not a function
    at MiCamera.discover (/usr/lib/node_modules/homebridge-mi-camera/index.js:46:22)
    at new MiCamera (/usr/lib/node_modules/homebridge-mi-camera/index.js:36:7)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:275:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)`

Does anyone can help me with?

Thanks in advance.

**Comment by jumpooger** [comment]
Hallo I have the same problem with the DAFANG

**Comment by Solusan** [comment]
Seems that Dafang only can works rooting it...

**Comment by francisco-navarro** [comment]
You mean executing homebridge with root?

**Comment by jumpooger** [comment]
You mean the Homebridge has to run in root mode?

**Comment by pax0707** [comment]
Xiaomi-Dafang-Hacks or something else?
